# Generated by Django 5.0.3 on 2024-03-24 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Elements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Наименование превого пунка вложенности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элементы меню",
                "verbose_name_plural": "Элементы меню",
            },
        ),
        migrations.DeleteModel(
            name="Nesting_1",
        ),
        migrations.DeleteModel(
            name="Nesting_2",
        ),
        migrations.AlterModelOptions(
            name="menus",
            options={"verbose_name": "Меню", "verbose_name_plural": "Меню"},
        ),
        migrations.AddField(
            model_name="elements",
            name="menu_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.menus",
                verbose_name="id меню",
            ),
        ),
        migrations.AddField(
            model_name="elements",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.elements",
                verbose_name="id родителя",
            ),
        ),
    ]
