# Generated by Django 5.0.3 on 2024-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_menus_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
