# Generated by Django 5.0.3 on 2024-03-24 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_elements_delete_nesting_1_delete_nesting_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elements",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name="Наименование превого пунка вложенности",
            ),
        ),
        migrations.AlterField(
            model_name="elements",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.elements",
                verbose_name="id родителя",
            ),
        ),
        migrations.AlterField(
            model_name="menus",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Наименование меню"
            ),
        ),
    ]
